"""add imagenet_map

Revision ID: 2d97dce810b9
Revises: 023c2c8c4c63
Create Date: 2025-08-30 16:42:10.167778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d97dce810b9'
down_revision: Union[str, Sequence[str], None] = '023c2c8c4c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.alter_column('imagenet_map', 'imagenet_label',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('imagenet_map', 'food_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('uq_imagenet_label', 'imagenet_map', type_='unique')
    op.create_index(op.f('ix_imagenet_map_food_key'), 'imagenet_map', ['food_key'], unique=False)
    op.create_index(op.f('ix_imagenet_map_id'), 'imagenet_map', ['id'], unique=False)
    op.create_index(op.f('ix_imagenet_map_imagenet_label'), 'imagenet_map', ['imagenet_label'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagenet_map_imagenet_label'), table_name='imagenet_map')
    op.drop_index(op.f('ix_imagenet_map_id'), table_name='imagenet_map')
    op.drop_index(op.f('ix_imagenet_map_food_key'), table_name='imagenet_map')
    op.create_unique_constraint('uq_imagenet_label', 'imagenet_map', ['imagenet_label'], postgresql_nulls_not_distinct=False)
    op.alter_column('imagenet_map', 'food_key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('imagenet_map', 'imagenet_label',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playing_with_neon_pkey')
    )
    # ### end Alembic commands ###
