"""add imagenet_map

Revision ID: 9908671303f0
Revises: 95baa66857d6
Create Date: 2025-08-30 15:56:43.762347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9908671303f0'
down_revision: Union[str, Sequence[str], None] = '95baa66857d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenet_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagenet_label', sa.String(length=64), nullable=False),
    sa.Column('food_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imagenet_label', name='uq_imagenet_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenet_map')
    # ### end Alembic commands ###
