"""add nutrition_info

Revision ID: d14d27c8645b
Revises: 2d97dce810b9
Create Date: 2025-08-30 17:01:49.694079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14d27c8645b'
down_revision: Union[str, Sequence[str], None] = '2d97dce810b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_key', sa.String(length=100), nullable=False),
    sa.Column('calories_per_100g', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('default_serving_g', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_info_food_key'), 'nutrition_info', ['food_key'], unique=True)
    op.create_index(op.f('ix_nutrition_info_id'), 'nutrition_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_info_id'), table_name='nutrition_info')
    op.drop_index(op.f('ix_nutrition_info_food_key'), table_name='nutrition_info')
    op.drop_table('nutrition_info')
    # ### end Alembic commands ###
